name = "MatrixShapedOperators"
uuid = "bac048d7-ba5f-40bb-941d-86aed15d6a0e"
version = "0.1.0"

[workspace]
projects = ["test", "docs"]

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
SciMLOperators = "c0aeaf25-5076-4817-a8d5-81caf7dfa961"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[extensions]
MatrixShapedOperatorsAdaptExt = "Adapt"
MatrixShapedOperatorsChainRulesCoreExt = "ChainRulesCore"
MatrixShapedOperatorsInverseFunctionsExt = "InverseFunctions"
MatrixShapedOperatorsLinearMapsExt = "LinearMaps"
MatrixShapedOperatorsSciMLOperatorsExt = "SciMLOperators"
MatrixShapedOperatorsSparseArraysExt = "SparseArrays"
MatrixShapedOperatorsStatisticsExt = "Statistics"
MatrixShapedOperatorsTestExt = "Test"

[compat]
Adapt = "3.4.1, 4"
ChainRulesCore = "1"
Compat = "4.10"
InverseFunctions = "0.1.17"
LinearAlgebra = "1"
PrecompileTools = "1.2"
LinearMaps = "3"
SciMLOperators = "1.15"
SparseArrays = "1"
Statistics = "1"
Test = "1"
julia = "1.10"
