[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
MatrixShapedOperators = "bac048d7-ba5f-40bb-941d-86aed15d6a0e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
Documenter = "1"

[sources]
MatrixShapedOperators = {path = ".."}
